spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/token?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root

  mail:
    host: smtp.mxhichina.com
    username: system@cocozl.com
    password: xxx
    properties:
      mail:
        smtp:
          port: 465
          ssl.enable: true
          starttls:
            enable: true
            required: true
      toAddr: yinguozi925107@126.com

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: io.wherein.cnstm.model

logging:
  level:
    io:
      wherein:
        cnstm:
          mapper: debug

url: http://uploadbeta.com/api/steemit/delegators/?cached&id=cnstm&hash=bcee701f176a53ac73463f1fd826431b